language: python

#which versions of python to test against
python:
  - "2.7"
  - "3.7"

# command to install dependencies
install:
  - pip install codecov

script: 
  - python -m unittest discover -v ./ci_play/ # command to run unit test
  - coverage run ./ci_play/test.py # command to run code coverage
  
after_success:
  bash <(curl -s https://codecov.io/bash)

addons:
  ssh_known_hosts: moon.scs.ryerson.ca

before_install:
  - openssl aes-256-cbc -K $encrypted_1a9a752e87dc_key -iv $encrypted_1a9a752e87dc_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

# deploy using rsync or scp
# setup ENV ($) variables in the web interface
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet 
     ${TRAVIS_BUILD_DIR}/ci_play      
     ${DEPLOY_USER}@${DEPLOY_SERVER}:/home/${DEPLOY_USER}
  on:
    branch: master
